# Permalinks
# permalink:        pretty
# permalink: /blog/:categories/:year/:month/:day/:title/

# Setup
title:            'Adson Batista'
tagline:          ' '
description:      '<img src="https://adsonbatista.github.io/images/public/hello.png"> Anotações sobre temas diversos.'
url:              http://receitas.adsonbatista.com

author:
  name:           'Adson Batista'
  # url:            https://twitter.com/mdo

paginate:         5
paginate_path: "/blog/page:num/"

gems:
  - jekyll-paginate
  
# Custom vars
version:          1.5.0

github:
  repo:           # https://github.com/poole/lanyon

theme: jekyll-theme-cayman